apiVersion: v1
kind: Service
metadata:
  name: web4api-deployment
  labels:
    app: web4api
spec:
  selector:
    app: web4api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 8080
  